//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp12
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int appointment_id { get; set; }
        public int client_id { get; set; }
        public int doctors_id { get; set; }
        public System.DateTime date { get; set; }
        public string comment { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Doctors Doctors { get; set; }
    }
}
